import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const { hash } = bcrypt;

const prisma = new PrismaClient();

export const WALL_OF_WATCHING_TITLES = [
  {
    externalMediaId: 67070,
    mediaType: "TV",
    domain: "ANIME",
    title: "Mob Psycho 100",
    posterPath: "https://image.tmdb.org/t/p/w500/dyqj0x5t2dO4z0L3bC4Y1bQ1mZ.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/m8396zK9L6rTz8X8Y2H5VbL.jpg",
    overview: "Shigeo Kageyama, an average middle school boy nicknamed Mob, is actually a powerful esper.",
    releaseDate: new Date("2016-07-12"),
    status: "WATCHING",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 10,
    totalEpisodes: 12,
    favorite: true,
    notes: "Season 1 finale arc is mind-blowing.",
  },
  {
    externalMediaId: 209867,
    mediaType: "TV",
    domain: "ANIME",
    title: "Solo Leveling",
    posterPath: "https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuClJiwxtJ.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/j3Z3bLhK4L7J5X9V2W5Y8bK.jpg",
    overview: "They say whatever does not kill you makes you stronger, but that's not the case for Sung Jinwoo.",
    releaseDate: new Date("2024-01-07"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: true,
    notes: "Igris fight was legendary animation.",
  },
  {
    externalMediaId: 21675,
    mediaType: "TV",
    domain: "ANIME",
    title: "Vampire Knight",
    posterPath: "https://image.tmdb.org/t/p/w500/z0T0oYq9WpE1c4uY.jpg",
    backdropPath: null,
    overview: "Cross Academy is attended by two groups of students: the Day Class and the Night Class.",
    releaseDate: new Date("2008-04-08"),
    status: "WATCHING",
    rating: 6,
    seasonNumber: 1,
    currentEpisode: 5,
    totalEpisodes: 13,
    favorite: false,
    notes: "Gothic mystery nostalgia vibe.",
  },
  {
    externalMediaId: 105658,
    mediaType: "TV",
    domain: "ANIME",
    title: "The Lost Vanguard",
    posterPath: "https://image.tmdb.org/t/p/w500/9b2N7T8hJ7k5mK9.jpg",
    backdropPath: null,
    overview: "In a world shattered by divine conflicts, the last vanguard stands against encroaching abyss.",
    releaseDate: new Date("2022-04-10"),
    status: "WATCHED",
    rating: 7,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: false,
    notes: "Solid 3D cultivation fantasy animation.",
  },
  {
    externalMediaId: 8392,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "My Neighbor Totoro",
    posterPath: "https://image.tmdb.org/t/p/w500/rtGDOe09gnhtOLf9v0vdB9OiIzy.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2teWOdeC16L8mD2F6YQ9y7X.jpg",
    overview: "Two sisters move to the country with their father to be closer to their hospitalized mother.",
    releaseDate: new Date("1988-04-16"),
    status: "WATCHED",
    rating: 7,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: false,
    notes: "Pure Ghibli comfort film.",
  },
  {
    externalMediaId: 100757,
    mediaType: "TV",
    domain: "ANIME",
    title: "Tokyo Revengers",
    posterPath: "https://image.tmdb.org/t/p/w500/arB34oZpZ6hXb0yv0kC8sHwZ0qM.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/y4aQpC4P5J8T2L8V6W9B3K2.jpg",
    overview: "Takemichi Hanagaki is a freelancer who's reached the absolute pits of despair in his life.",
    releaseDate: new Date("2021-04-11"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 24,
    totalEpisodes: 24,
    favorite: true,
    notes: "Bloody Halloween arc kept me on the edge of my seat.",
  },
  {
    externalMediaId: 61374,
    mediaType: "TV",
    domain: "ANIME",
    title: "Tokyo Ghoul",
    posterPath: "https://image.tmdb.org/t/p/w500/2tO6fGg1eHk1M0wL2sA4jZ3v8qP.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/5b2X4L5V7K8T9Y2W6J1.jpg",
    overview: "A Tokyo college student is attacked by a ghoul, a superpowered human who feeds on human flesh.",
    releaseDate: new Date("2014-07-04"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: true,
    notes: "Unravel soundtrack and final episode transformation.",
  },
  {
    externalMediaId: 568160,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Weathering With You",
    posterPath: "https://image.tmdb.org/t/p/w500/qgr5Tdu2QmzbtTXUR9UmEUJW17U.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/c4rF5L8P6Y2J8K9.jpg",
    overview: "During the summer of his high school freshman year, Hodaka runs away from his remote island home to Tokyo.",
    releaseDate: new Date("2019-07-19"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Makoto Shinkai's rain visuals and RADWIMPS songs are magic.",
  },
  {
    externalMediaId: 1429,
    mediaType: "TV",
    domain: "ANIME",
    title: "Attack on Titan",
    posterPath: "https://image.tmdb.org/t/p/w500/8C5gDxnB0iM5P0QpX7qV8d0yv4.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hT3A48opU8eOQ1Z2W.jpg",
    overview: "Several hundred years ago, humans were nearly exterminated by titans.",
    releaseDate: new Date("2013-04-07"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 25,
    totalEpisodes: 25,
    favorite: true,
    notes: "One of the greatest modern anime stories ever written.",
  },
  {
    externalMediaId: 489931,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Attack on Titan: The Roar of Awakening",
    posterPath: "https://image.tmdb.org/t/p/w500/u3B2KiT2V0w1u8b9C0a2d3e4f5.jpg",
    backdropPath: null,
    overview: "The compilation film covering Season 2 with enhanced sound and extra footage.",
    releaseDate: new Date("2018-01-13"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Reiner and Bertholdt reveal scene never gets old.",
  },
  {
    externalMediaId: 61663,
    mediaType: "TV",
    domain: "ANIME",
    title: "Your Lie in April",
    posterPath: "https://image.tmdb.org/t/p/w500/IGPsn7iS4zC3zQ2m4A2b3c4d5e.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9vL8F2V7X6M5Y1.jpg",
    overview: "Kosei Arima is a piano prodigy who lost his ability to play after his mother's death.",
    releaseDate: new Date("2014-10-10"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 1,
    currentEpisode: 22,
    totalEpisodes: 22,
    favorite: true,
    notes: "Emotional masterpiece. The final letter broke my heart.",
  },
  {
    externalMediaId: 129,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Spirited Away",
    posterPath: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/bSXfUsLBRxAPmm9Dx9kdUG1B9gq.jpg",
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits.",
    releaseDate: new Date("2001-07-20"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Miyazaki's immortal opus. Joe Hisaishi's One Summer's Day.",
  },
  {
    externalMediaId: 88523,
    mediaType: "TV",
    domain: "ANIME",
    title: "Battle Through the Heavens",
    posterPath: "https://image.tmdb.org/t/p/w500/4e9j4P1k3l5m6n7o8.jpg",
    backdropPath: null,
    overview: "Xiao Yan is a genius who suddenly loses all his powers in a land where strength rules.",
    releaseDate: new Date("2017-01-07"),
    status: "WATCHED",
    rating: 7,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: false,
    notes: "High octane donghua action and flame abilities.",
  },
  {
    externalMediaId: 63926,
    mediaType: "TV",
    domain: "ANIME",
    title: "One Punch Man",
    posterPath: "https://image.tmdb.org/t/p/w500/iE3s0lG5vtLm8ip0y9U8be0y29f.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7X2V6M9L5J8.jpg",
    overview: "Saitama is a hero who only became a hero for fun after training so hard he lost all his hair.",
    releaseDate: new Date("2015-10-05"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: true,
    notes: "Madhouse season 1 animation is unrivaled.",
  },
  {
    externalMediaId: 119053,
    mediaType: "TV",
    domain: "ANIME",
    title: "Summer Time Rendering",
    posterPath: "https://image.tmdb.org/t/p/w500/7WsyChvXW98a58u9d0g.jpg",
    backdropPath: null,
    overview: "Upon hearing of Ushio's death, Shinpei returns to his hometown of Hitogashima island.",
    releaseDate: new Date("2022-04-15"),
    status: "WATCHED",
    rating: 8,
    seasonNumber: 1,
    currentEpisode: 25,
    totalEpisodes: 25,
    favorite: false,
    notes: "Brilliant time-loop suspense thriller from start to finish.",
  },
  {
    externalMediaId: 46260,
    mediaType: "TV",
    domain: "ANIME",
    title: "Naruto",
    posterPath: "https://image.tmdb.org/t/p/w500/xppeysfvDKVx77CV0gvjkTEWz3V.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9rM8Y2L3V6.jpg",
    overview: "Naruto Uzumaki, a hyperactive and knuckle-headed ninja, searches for recognition.",
    releaseDate: new Date("2002-10-03"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 220,
    totalEpisodes: 220,
    favorite: true,
    notes: "Chunin exams and Sasuke retrieval arcs are peak shonen.",
  },
  {
    externalMediaId: 198370,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "The Garden of Words",
    posterPath: "https://image.tmdb.org/t/p/w500/3p0Yj2sWvPqY4Z5b6c7d8e9f0.jpg",
    backdropPath: null,
    overview: "A 15-year-old aspiring shoemaker skips morning school during rainy season to sketch in a Japanese garden.",
    releaseDate: new Date("2013-05-31"),
    status: "WATCHED",
    rating: 8,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: false,
    notes: "Short, poetic, stunning depiction of rain and solace.",
  },
  {
    externalMediaId: 378064,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "A Silent Voice: The Movie",
    posterPath: "https://image.tmdb.org/t/p/w500/tuFaWiqX0TXRWuNWxNFJJ5nfJa8.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/5ELkK5Z1V9bL4.jpg",
    overview: "Shoya Ishida starts bullying the new girl in class, Shoko Nishimiya, because she is deaf.",
    releaseDate: new Date("2016-09-17"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Kyoto Animation's triumph of redemption and empathy.",
  },
  {
    externalMediaId: 508883,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "The Boy and the Heron",
    posterPath: "https://image.tmdb.org/t/p/w500/jDQBidImL4TmmSLaKf897aQ8v8x.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/6K2L4M8J9.jpg",
    overview: "While the Second World War rages, teenage Mahito struggles to settle into a new town.",
    releaseDate: new Date("2023-07-14"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Miyazaki's autobiographical surrealist meditation on loss.",
  },
  {
    externalMediaId: 504253,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "I Want to Eat Your Pancreas",
    posterPath: "https://image.tmdb.org/t/p/w500/A8v603uKqF6W0A7a2B1c0D3e4f.jpg",
    backdropPath: null,
    overview: "An aloof boy stumbles upon a secret diary in a hospital belonging to his popular classmate.",
    releaseDate: new Date("2018-09-01"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Devastatingly beautiful story about choosing to live fully.",
  },
  {
    externalMediaId: 372058,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Your Name",
    posterPath: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6ditYeZAv92d.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7r57b1t0W1.jpg",
    overview: "High schoolers Mitsuha and Taki are complete strangers living separate lives until they swap bodies.",
    releaseDate: new Date("2016-08-26"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Flawless soundtrack, astronomical animation, breathtaking romance.",
  },
  {
    externalMediaId: 85937,
    mediaType: "TV",
    domain: "ANIME",
    title: "Demon Slayer: Kimetsu no Yaiba",
    posterPath: "https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9yM6X8V1.jpg",
    overview: "Tanjiro Kamado sets out to become a demon slayer after his family is slaughtered.",
    releaseDate: new Date("2019-04-06"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 26,
    totalEpisodes: 26,
    favorite: true,
    notes: "Ufotable episode 19 Hinokami Kagura made history.",
  },
  {
    externalMediaId: 635302,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Demon Slayer: Mugen Train",
    posterPath: "https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODurY5z6SYAmPnQEB.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/3G2L4M8J9.jpg",
    overview: "Tanjiro and the group join Flame Hashira Kyojuro Rengoku on a train mission.",
    releaseDate: new Date("2020-10-16"),
    status: "WATCHED",
    rating: 8,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: false,
    notes: "Set your heart ablaze. Rengoku was a true legend.",
  },
  {
    externalMediaId: 139160,
    mediaType: "TV",
    domain: "ANIME",
    title: "Demon Slayer: Entertainment District",
    posterPath: "https://image.tmdb.org/t/p/w500/7aEa6sJk1l2m3n4.jpg",
    backdropPath: null,
    overview: "Tanjiro, Zenitsu, and Inosuke infiltrate the Yoshiwara red-light district with Sound Hashira Tengen Uzui.",
    releaseDate: new Date("2021-12-05"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 2,
    currentEpisode: 11,
    totalEpisodes: 11,
    favorite: true,
    notes: "Tengen Uzui vs Gyutaro is the peak of anime fight choreography.",
  },
  {
    externalMediaId: 51739,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "The Secret World of Arrietty",
    posterPath: "https://image.tmdb.org/t/p/w500/w7D5l0k1m2n3o4.jpg",
    backdropPath: null,
    overview: "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity beneath the floorboards.",
    releaseDate: new Date("2010-07-17"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: false,
    notes: "Charming miniature perspective and Cecile Corbel's Celtic harp.",
  },
  {
    externalMediaId: 984501,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Lonely Castle in the Mirror",
    posterPath: "https://image.tmdb.org/t/p/w500/8d8a7k0k1m2n3o4.jpg",
    backdropPath: null,
    overview: "Seven students who avoid going to school find themselves drawn into a magical castle.",
    releaseDate: new Date("2022-12-23"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Gentle mystery that turns into an unforgettable emotional puzzle.",
  },
  {
    externalMediaId: 95479,
    mediaType: "TV",
    domain: "ANIME",
    title: "JUJUTSU KAISEN",
    posterPath: "https://image.tmdb.org/t/p/w500/aI1fm7H2rhfRxnwWIdVACR3k1fO.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/gmP5V6.jpg",
    overview: "Yuji Itadori swallows a cursed finger to save a friend and becomes the host of Sukuna.",
    releaseDate: new Date("2020-10-03"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 24,
    totalEpisodes: 24,
    favorite: true,
    notes: "Domain Expansions and Gojo's hollow purple.",
  },
  {
    externalMediaId: 810693,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Jujutsu Kaisen 0",
    posterPath: "https://image.tmdb.org/t/p/w500/3pTwOi2AcpeaRJZZM0085pD7dK7.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9rM8Y2L3V6.jpg",
    overview: "Yuta Okkotsu is haunted by the spirit of his childhood friend Rika, who died in a traffic accident.",
    releaseDate: new Date("2021-12-24"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Yuta and Rika's pure love curse. Spectacular cinema.",
  },
  {
    externalMediaId: 4935,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Howl's Moving Castle",
    posterPath: "https://image.tmdb.org/t/p/w500/6p0K2eM6iE8qY9a0B1c2d3e4f5.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hT3A48opU8eOQ1Z2W.jpg",
    overview: "Sophie, an 18-year-old milliner, is transformed into an elderly woman by a vengeful witch.",
    releaseDate: new Date("2004-11-20"),
    status: "WATCHED",
    rating: 10,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Merry-Go-Round of Life and Calcifer's heart.",
  },
  {
    externalMediaId: 588320,
    mediaType: "MOVIE",
    domain: "MOVIE",
    title: "Hello World",
    posterPath: "https://image.tmdb.org/t/p/w500/k0Y2l3m4n5.jpg",
    backdropPath: null,
    overview: "A sci-fi romantic drama set in Kyoto in the year 2027 where a boy meets his future self.",
    releaseDate: new Date("2019-09-20"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 1,
    totalEpisodes: 1,
    favorite: true,
    notes: "Underrated sci-fi mind-bender with heart.",
  },
  {
    externalMediaId: 1399,
    mediaType: "TV",
    domain: "ANIME",
    title: "Death Note",
    posterPath: "https://image.tmdb.org/t/p/w500/iigTJJskR1PcjjPLiIlWuF9io74.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9rM8Y2L3V6.jpg",
    overview: "Light Yagami finds a notebook with the power to kill anyone whose name is written in it.",
    releaseDate: new Date("2006-10-04"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 37,
    totalEpisodes: 37,
    favorite: true,
    notes: "The mental cat-and-mouse duel between Light and L is timeless.",
  },
  {
    externalMediaId: 114410,
    mediaType: "TV",
    domain: "ANIME",
    title: "Chainsaw Man",
    posterPath: "https://image.tmdb.org/t/p/w500/npdB6eFz4qt9CdFOEgCVJRJte2.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hT3A48opU8eOQ1Z2W.jpg",
    overview: "Denji is a teenage boy living with a Chainsaw Devil named Pochita.",
    releaseDate: new Date("2022-10-12"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: true,
    notes: "12 unique ending themes and cinematic film direction by Nakayama.",
  },
  {
    externalMediaId: 207399,
    mediaType: "TV",
    domain: "ANIME",
    title: "The Dangers in My Heart",
    posterPath: "https://image.tmdb.org/t/p/w500/6l0m1n2o3.jpg",
    backdropPath: null,
    overview: "Fascinated by murder and all things grotesque, Kyotaro daydreams about acting out his twisted fantasies.",
    releaseDate: new Date("2023-04-02"),
    status: "WATCHED",
    rating: 8,
    seasonNumber: 1,
    currentEpisode: 12,
    totalEpisodes: 12,
    favorite: false,
    notes: "Wholesome character growth and library encounters.",
  },
  {
    externalMediaId: 73223,
    mediaType: "TV",
    domain: "ANIME",
    title: "Black Clover",
    posterPath: "https://image.tmdb.org/t/p/w500/opXUSwE8203m9e4b6c8d0e1f2.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9rM8Y2L3V6.jpg",
    overview: "Asta and Yuno were abandoned at the same church on the same day. Raised together, they learned of the 'Wizard King.'",
    releaseDate: new Date("2017-10-03"),
    status: "WATCHED",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 170,
    totalEpisodes: 170,
    favorite: true,
    notes: "My magic is never giving up! Black Bulls family forever.",
  },
  // Active continue watching title matching the floating bar
  {
    externalMediaId: 31910,
    mediaType: "TV",
    domain: "ANIME",
    title: "Naruto Shippūden",
    posterPath: "https://image.tmdb.org/t/p/w500/kV27inQaec007TvlRBVOzD6L64r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9rM8Y2L3V6.jpg",
    overview: "Naruto Uzumaki wants to be the best ninja in the land.",
    releaseDate: new Date("2007-02-15"),
    status: "WATCHING",
    rating: 9,
    seasonNumber: 1,
    currentEpisode: 501,
    totalEpisodes: 500,
    favorite: true,
    notes: "Epic fourth shinobi world war finale.",
  },
];

async function main() {
  console.log("🌱 Seeding WatchVerse database with 'Wall of Watching'...");

  const demoEmail = "demo@watchverse.com";
  const passwordHash = await hash("password123", 10);

  // Upsert Demo User
  const demoUser = await prisma.user.upsert({
    where: { email: demoEmail },
    update: {
      name: "Alex Rivera",
      passwordHash,
    },
    create: {
      email: demoEmail,
      name: "Alex Rivera",
      passwordHash,
    },
  });

  console.log(`👤 User ready: ${demoUser.email} (${demoUser.id})`);

  // Clear existing entries for demo user
  await prisma.watchEntry.deleteMany({
    where: { userId: demoUser.id },
  });

  for (const entry of WALL_OF_WATCHING_TITLES) {
    await prisma.watchEntry.create({
      data: {
        userId: demoUser.id,
        externalMediaId: entry.externalMediaId,
        mediaType: entry.mediaType,
        domain: entry.domain,
        title: entry.title,
        posterPath: entry.posterPath,
        backdropPath: entry.backdropPath,
        overview: entry.overview,
        releaseDate: entry.releaseDate,
        status: entry.status,
        rating: entry.rating,
        seasonNumber: entry.seasonNumber,
        currentEpisode: entry.currentEpisode,
        totalEpisodes: entry.totalEpisodes,
        favorite: entry.favorite,
        notes: entry.notes,
      },
    });
  }

  console.log(`✅ Successfully seeded ${WALL_OF_WATCHING_TITLES.length} Wall of Watching titles!`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
